# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Connection.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog_connection(object):
    def setupUi(self, dialog_connection):
        dialog_connection.setObjectName("dialog_connection")
        dialog_connection.resize(513, 212)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_connection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_options = QtWidgets.QTabWidget(dialog_connection)
        self.tabWidget_options.setObjectName("tabWidget_options")
        self.widget_main_options = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_main_options.sizePolicy().hasHeightForWidth())
        self.widget_main_options.setSizePolicy(sizePolicy)
        self.widget_main_options.setObjectName("widget_main_options")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget_main_options)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_host = QtWidgets.QLabel(self.widget_main_options)
        self.label_host.setObjectName("label_host")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_host)
        self.lineEdit_host = QtWidgets.QLineEdit(self.widget_main_options)
        self.lineEdit_host.setText("")
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_host)
        self.label_user = QtWidgets.QLabel(self.widget_main_options)
        self.label_user.setObjectName("label_user")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_user)
        self.lineEdit_user = QtWidgets.QLineEdit(self.widget_main_options)
        self.lineEdit_user.setText("")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_user)
        self.label_secret = QtWidgets.QLabel(self.widget_main_options)
        self.label_secret.setObjectName("label_secret")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_secret)
        self.lineEdit_secret = QtWidgets.QLineEdit(self.widget_main_options)
        self.lineEdit_secret.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_secret.setObjectName("lineEdit_secret")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_secret)
        self.tabWidget_options.addTab(self.widget_main_options, "")
        self.widget_additional_options = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_additional_options.sizePolicy().hasHeightForWidth())
        self.widget_additional_options.setSizePolicy(sizePolicy)
        self.widget_additional_options.setObjectName("widget_additional_options")
        self.formLayout_4 = QtWidgets.QFormLayout(self.widget_additional_options)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_port = QtWidgets.QLabel(self.widget_additional_options)
        self.label_port.setObjectName("label_port")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(self.widget_additional_options)
        self.lineEdit_port.setText("22")
        self.lineEdit_port.setMaxLength(4)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_port)
        self.label_terminal_type = QtWidgets.QLabel(self.widget_additional_options)
        self.label_terminal_type.setObjectName("label_terminal_type")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_terminal_type)
        self.lineEdit_terminal_type = QtWidgets.QLineEdit(self.widget_additional_options)
        self.lineEdit_terminal_type.setText("xfce4-terminal")
        self.lineEdit_terminal_type.setObjectName("lineEdit_terminal_type")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_terminal_type)
        self.tabWidget_options.addTab(self.widget_additional_options, "")
        self.verticalLayout.addWidget(self.tabWidget_options)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.pushButton_load = QtWidgets.QPushButton(dialog_connection)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_buttons.addWidget(self.pushButton_load)
        self.pushButton_connect = QtWidgets.QPushButton(dialog_connection)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout_buttons.addWidget(self.pushButton_connect)
        self.pushButton_exit = QtWidgets.QPushButton(dialog_connection)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout_buttons.addWidget(self.pushButton_exit)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)

        self.retranslateUi(dialog_connection)
        self.tabWidget_options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialog_connection)

    def retranslateUi(self, dialog_connection):
        _translate = QtCore.QCoreApplication.translate
        dialog_connection.setWindowTitle(_translate("dialog_connection", "Система удаленного администрирования сервера"))
        self.label_host.setText(_translate("dialog_connection", "Адрес хоста"))
        self.label_user.setText(_translate("dialog_connection", "Имя пользователя"))
        self.label_secret.setText(_translate("dialog_connection", "Пароль"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.widget_main_options), _translate("dialog_connection", "Параметры соеденения"))
        self.label_port.setText(_translate("dialog_connection", "Порт"))
        self.label_terminal_type.setText(_translate("dialog_connection", "Тип терминала"))
        self.tabWidget_options.setTabText(self.tabWidget_options.indexOf(self.widget_additional_options), _translate("dialog_connection", "Дополнительные параметры"))
        self.pushButton_load.setText(_translate("dialog_connection", "Загрузить настройки из файла"))
        self.pushButton_connect.setText(_translate("dialog_connection", "Подключиться"))
        self.pushButton_exit.setText(_translate("dialog_connection", "Выход"))

